### ISSUE TITLE
Change data format into 1 event per file (YAML+Front Matter)

### ISSUE THREAD

**Issue by dtinth** [ThaiProgrammer/tech-events-calendar#42]
Now, there are many events in this project. Adding new events becomes more cumbersome.

## Proposal

Instead of putting all events inside a single file, README.md, separate each event into a Markdown file with YAML front matter. This should allow easier parsing!

### Before

Everything in README.md

```markdown
### <a name="bkk-web-pwa-meetup-42703818270"></a> 6 (Tue): BKK Web Meetup: Progressive Web Apps (PWA) — Mobile app's future

| | | |
| --- | --- | --- |
| 🏷 | Meetup | Web, Mobile, JavaScript |
| 📍 | [Launchpad Co., Ltd](https://www.google.com/maps/place/Launchpad+Co.,+Ltd/@13.721292,100.5220373,17z/data=!3m1!4b1!4m5!3m4!1s0x30e298cdd6e8270d:0x7e9aa39655924697!8m2!3d13.721292!4d100.524226) |
| ⌚️ | 19:00~22:00 |
| 🎟 | [eventbrite.com](https://www.eventbrite.com/e/progressive-web-apps-pwa-mobile-apps-future-tickets-42703818270) | FREE |
| ✅ | [Facebook Event](https://www.facebook.com/events/195556101180309/) |

Short introduction.

> Details paragraph 1
>
> Details paragraph 2
```

### After

One event per file

```yaml
---
id: bkk-web-pwa-meetup-42703818270
title: BKK Web Meetup: Progressive Web Apps (PWA) — Mobile app's future
date: 2018-03-06
time:
  - 19:00 ~ 22:00
categories:
  - Meetup
topics:
  - Web
  - Mobile
  - JavaScript
location:
  title: Launchpad Co., Ltd
  url: https://www.google.com/maps/place/Launchpad+Co.,+Ltd/@13.721292,100.5220373,17z/data=!3m1!4b1!4m5!3m4!1s0x30e298cdd6e8270d:0x7e9aa39655924697!8m2!3d13.721292!4d100.524226
summary: Short introduction.
---
Details paragraph 1

Details paragraph 2
```

### File organization

```
data/
  2018-03/
    06-bkk-web-pwa-meetup.md
```

**Note:** File name can actually be anything (but better make it descriptive). It is not used when parsing. Event is only identified via explicit ID (which must be unique). This allows us to change the format again in the future if needed, without impacting existing event IDs.

### Tasks

- [x] ADR
- [x] Convert event files to md+yaml files (this can be done with a script)
- [x] Make the JSON generation script read the md+yaml files instead of parsing README.md
    - [x] Parse date properly
        - Single date: `2018-02-07`
        - Date range: `2018-02-07 ~ 2018-02-09`
    - [x] Parse timetable properly
        - Time: `18:00 ~ 21:00`
        - Array
        - With agenda: `18:00 ~ 21:00 (Meetup)`
        - With extension: `18:00 ~ 21:00++`
- [x] Update docs (contribution guide).
- [x] Make sure redirection service and homepage still works!
